#!/bin/sh
echo "Are you SURE you want to wipe out your database and re-initialize it?"
echo "All data related to this application will be LOST!!!"
echo "Enter yes if you really want to do this."
read a
if [ "$a" != "yes" ]; then
	exit 1
fi

# Figure out where the current script lives.  Run from that directory.
scriptDir="`dirname \"$0\"`"
[ "$scriptDir" != "" ] && cd "$scriptDir"
scriptDir="`pwd`"

database='pfm'
#username='pfm'
#password='123pFm321'

mysql -D $database -u root < sql
