#!/bin/sh
#
# Use to initialize a test environement
#
if [ $# -ne 2 ] ; then
  echo "Usage: $0 <prod-pase-dir> <test-base-dir>" 1>&2
  exit 1
fi

src="$(realpath -e $1)" ; [ -z "$src" ] &&  exit 2
dst="$(realpath -e $2)" ; [ -z "$dst" ] &&  exit 3
tmp=$(mktemp)
trap "rm -f $tmp" EXIT;

echo "Are you SURE you want to wipe out your database and re-initialize it?"
echo "All data related to this application will be LOST!!!"
echo "Enter yes if you really want to do this."
read a
if [ "$a" != "yes" ]; then
	exit 1
fi

php $src/index.php /obackup $tmp
php $dst/index.php /orestore $tmp
rm -f $dst/data/*.php $dst/data/Importers/*.php
cp $src/data/*.php $dst/data
cp $src/data/Importers/*.php $dst/data/Importers
chcon -R -t httpd_sys_rw_content_t $dst/data
find $dst/data -type f -name '*.php' -print0 | xargs -0 chmod a+w
